/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import Classes.Player;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.OK_OPTION;
/**
 *
 * @author marco
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   
    Player player1 = new Player("X");
    Player player2 = new Player("O");
    
           
    
    boolean turn = false;
    boolean win = false;
    private void whosTurn(){        
        turn = turn == false;
    }
    
    private void win(javax.swing.JButton position1, javax.swing.JButton position2, javax.swing.JButton position3){

            
            if(position1.getText().equals(position2.getText()) && position1.getText().equals(position3.getText())){
                win = true;
                if(JOptionPane.showConfirmDialog(null,position1.getText() + " Win, Wanna restart?", null, OK_CANCEL_OPTION) == OK_OPTION){                
                    this.dispose();
                    new TelaInicial().setVisible(true);               
                }else{
                    this.dispose();
                }              
            }
        
        
    }
    
    private void draw(){
        if(position1.isEnabled() == false && position2.isEnabled() == false && position3.isEnabled() == false && position4.isEnabled() == false && position5.isEnabled() == false &&
        position6.isEnabled() == false && position7.isEnabled() == false && position8.isEnabled() == false && position9.isEnabled() == false && win == false){            
            
            if(JOptionPane.showConfirmDialog(null," Draw, Wanna restart?", null, OK_CANCEL_OPTION) == OK_OPTION){                
                this.dispose();
                new TelaInicial().setVisible(true);                
            }else{
                this.dispose();
            }                
        }
    }    
                    
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        subTitle = new javax.swing.JLabel();
        position9 = new javax.swing.JButton();
        position1 = new javax.swing.JButton();
        position2 = new javax.swing.JButton();
        position3 = new javax.swing.JButton();
        position6 = new javax.swing.JButton();
        position5 = new javax.swing.JButton();
        position4 = new javax.swing.JButton();
        position7 = new javax.swing.JButton();
        position8 = new javax.swing.JButton();
        board = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TicTacToe");
        setMinimumSize(new java.awt.Dimension(730, 637));
        setResizable(false);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("TicTacToe");
        getContentPane().add(title);
        title.setBounds(150, 60, 433, 56);

        subTitle.setText("Click in the board to play");
        getContentPane().add(subTitle);
        subTitle.setBounds(300, 130, 150, 16);

        position9.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position9.setBorder(null);
        position9.setContentAreaFilled(false);
        position9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position9ActionPerformed(evt);
            }
        });
        getContentPane().add(position9);
        position9.setBounds(420, 410, 100, 100);

        position1.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position1.setBorder(null);
        position1.setContentAreaFilled(false);
        position1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position1ActionPerformed(evt);
            }
        });
        getContentPane().add(position1);
        position1.setBounds(200, 190, 100, 100);

        position2.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position2.setBorder(null);
        position2.setContentAreaFilled(false);
        position2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position2.setMaximumSize(new java.awt.Dimension(72, 23));
        position2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position2ActionPerformed(evt);
            }
        });
        getContentPane().add(position2);
        position2.setBounds(320, 190, 80, 100);

        position3.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position3.setBorder(null);
        position3.setContentAreaFilled(false);
        position3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position3ActionPerformed(evt);
            }
        });
        getContentPane().add(position3);
        position3.setBounds(420, 190, 100, 100);

        position6.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position6.setBorder(null);
        position6.setContentAreaFilled(false);
        position6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position6ActionPerformed(evt);
            }
        });
        getContentPane().add(position6);
        position6.setBounds(420, 310, 100, 80);

        position5.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position5.setBorder(null);
        position5.setContentAreaFilled(false);
        position5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position5ActionPerformed(evt);
            }
        });
        getContentPane().add(position5);
        position5.setBounds(320, 310, 80, 80);

        position4.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position4.setBorder(null);
        position4.setContentAreaFilled(false);
        position4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position4ActionPerformed(evt);
            }
        });
        getContentPane().add(position4);
        position4.setBounds(200, 310, 100, 80);

        position7.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position7.setBorder(null);
        position7.setContentAreaFilled(false);
        position7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position7ActionPerformed(evt);
            }
        });
        getContentPane().add(position7);
        position7.setBounds(200, 410, 100, 100);

        position8.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        position8.setBorder(null);
        position8.setContentAreaFilled(false);
        position8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        position8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                position8ActionPerformed(evt);
            }
        });
        getContentPane().add(position8);
        position8.setBounds(320, 410, 80, 100);

        board.setBackground(new java.awt.Color(255, 255, 255));
        board.setFont(new java.awt.Font("Calibri", 0, 48)); // NOI18N
        board.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/TicTacToe.png"))); // NOI18N
        board.setToolTipText("");
        board.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        board.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(board);
        board.setBounds(190, 180, 340, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void position1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position1ActionPerformed
        whosTurn();
        if(turn == true){
            this.position1.setText(player1.getLetter());
        }else if((turn == false)){
            this.position1.setText(player2.getLetter());
        }
        
        position1.setEnabled(false);
        
        this.win(position1, position2, position3);
        this.win(position1, position4, position7);
        this.win(position1, position5, position9);
        this.draw();
    }//GEN-LAST:event_position1ActionPerformed

    private void position2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position2ActionPerformed
        whosTurn();
        if(turn == true){
            this.position2.setText(player1.getLetter());
        }else if((turn == false)){
            this.position2.setText(player2.getLetter());
        }
        
        position2.setEnabled(false);
        
        this.win(position1, position2, position3);
        this.win(position2, position5, position8);
        this.draw();
    }//GEN-LAST:event_position2ActionPerformed

    private void position3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position3ActionPerformed
        whosTurn();
        if(turn == true){
            this.position3.setText(player1.getLetter());
        }else if((turn == false)){
            this.position3.setText(player2.getLetter());
        }
        
        position3.setEnabled(false);
        
        this.win(position1, position2, position3);
        this.win(position3, position6, position9);
        this.win(position3, position5, position7);
        this.draw();
    }//GEN-LAST:event_position3ActionPerformed

    private void position4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position4ActionPerformed
        whosTurn();
        if(turn == true){
            this.position4.setText(player1.getLetter());
        }else if((turn == false)){
            this.position4.setText(player2.getLetter());
        }
        
        position4.setEnabled(false);
        
        this.win(position1, position4, position7);
        this.win(position4, position5, position6);
        this.draw();
    }//GEN-LAST:event_position4ActionPerformed

    private void position5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position5ActionPerformed
        whosTurn();
        if(turn == true){
            this.position5.setText(player1.getLetter());
        }else if((turn == false)){
            this.position5.setText(player2.getLetter());
        }
        
        position5.setEnabled(false);
        
        this.win(position1, position5, position9);
        this.win(position4, position5, position6);
        this.win(position3, position5, position7);
        this.win(position2, position5, position8);
        this.draw();
    }//GEN-LAST:event_position5ActionPerformed

    private void position6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position6ActionPerformed
        whosTurn();
        if(turn == true){
            this.position6.setText(player1.getLetter());
        }else if((turn == false)){
            this.position6.setText(player2.getLetter());
        }
        
        position6.setEnabled(false);
        
        this.win(position4, position5, position6);
        this.win(position3, position6, position9);
        this.draw();
    }//GEN-LAST:event_position6ActionPerformed

    private void position7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position7ActionPerformed
        whosTurn();
        if(turn == true){
            this.position7.setText(player1.getLetter());
        }else if((turn == false)){
            this.position7.setText(player2.getLetter());
        }
        
        position7.setEnabled(false);
        
        this.win(position1, position4, position7);
        this.win(position3, position5, position7);
        this.win(position7, position8, position9);
        this.draw();
    }//GEN-LAST:event_position7ActionPerformed

    private void position8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position8ActionPerformed
        whosTurn();
        if(turn == true){
            this.position8.setText(player1.getLetter());
        }else if((turn == false)){
            this.position8.setText(player2.getLetter());
        }
        
        position8.setEnabled(false);
        
        this.win(position7, position8, position9);
        this.win(position2, position5, position8);
        this.draw();
    }//GEN-LAST:event_position8ActionPerformed

    private void position9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_position9ActionPerformed
        whosTurn();
        if(turn == true){
            this.position9.setText(player1.getLetter());
        }else if((turn == false)){
            this.position9.setText(player2.getLetter());
        }
        
        position9.setEnabled(false);
        
        this.win(position7, position8, position9);
        this.win(position1, position5, position9);
        this.win(position3, position6, position9);
        this.draw();
    }//GEN-LAST:event_position9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel board;
    private javax.swing.JButton position1;
    private javax.swing.JButton position2;
    private javax.swing.JButton position3;
    private javax.swing.JButton position4;
    private javax.swing.JButton position5;
    private javax.swing.JButton position6;
    private javax.swing.JButton position7;
    private javax.swing.JButton position8;
    private javax.swing.JButton position9;
    private javax.swing.JLabel subTitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
